# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'MyCloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'TangramKit'
	pod 'R.swift'
	pod 'DynamicColor'
	pod 'QMUIKit'
	# swift 网络请求
	# pod 'Moya'
	pod 'Moya/RxSwift'
	pod 'NSObject+Rx'
	pod 'HandyJSON'
  # 提示框架
	pod 'MBProgressHUD'
  # OC 图片加载缓存
	pod 'SDWebImage'
  # Swift 图片加载缓存
	pod 'Kingfisher'
  # Swift 字符串扩展
	pod 'SwifterSwift'
  # Swift 发布订阅
	pod 'SwiftEventBus'


  # Pods for MyCloudMusic

  target 'MyCloudMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCloudMusicUITests' do
    # Pods for testing
  end

end
